spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

  datasource:
    url: " jdbc:h2:tcp://localhost/~/desktop/Programming/진심/loginapi"
    username: sa
    password: 1234

    driver-class-name: org.h2.Driver